export const API_BASE_URL = process.env.VUE_APP_API_BASE_URL || 'http://localhost:3000/api'

export const states = [
  'Aguascalientes',
  'Baja Norte',
  'Baja Sur',
  'Campeche',
  'Chihuahua',
  'Chiapas',
  'Coahuila',
  'Colima',
  'Durango',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'México',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo ',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana ',
  'San ',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
]
